### PR TITLE
Updatec calculation error

### PR DESCRIPTION
**Pull request by GoFroggyRun**

### CODE REVIEW

**Comment by MattHJensen** [comment]
I think the right solution on rounding is probably to use the raw numbers in all calculations but to round everything to 10ths before it is displayed. Looks like right now you may be using rounded numbers in the calculations.

**Comment by GoFroggyRun** [comment]
Thanks for the tips. Seems good to go.

https://ospc.shinyapps.io/border-adjustment-calculator/

On Dec 22, 2016, at 4:23 PM, Matt Jensen <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the right solution on rounding is probably to use the raw numbers in all calculations but to round everything to 10ths before it is displayed. Looks like right now you may be using rounded numbers in the calculations.

**Comment by GoFroggyRun** [comment]
After several tests, the rounding errors seem have nothing to do with the way I rounded them. Even I used the original values to calculate (previously I was using one more decimal, which should be essentially the same), the issue persists.

My fix, for the moment, would be keeping two decimals for the final results-after tax profits. I haven’t yet found any inconsistency in this case. I’ll try to fix the problem for one decimal as well.

On Dec 22, 2016, at 4:55 PM, Sean Wang <Sean.Wang@AEI.org<mailto:Sean.Wang@aei.org>> wrote:

Thanks for the tips. Seems good to go.

https://ospc.shinyapps.io/border-adjustment-calculator/

On Dec 22, 2016, at 4:23 PM, Matt Jensen <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the right solution on rounding is probably to use the raw numbers in all calculations but to round everything to 10ths before it is displayed. Looks like right now you may be using rounded numbers in the calculations.

**Comment by MattHJensen** [comment]
Let's keep the tenths place even if it creates inconsistencies while you try to identify the cause of the inconsistencies.

On Dec 22, 2016, at 6:37 PM, Sean.Wang <notifications@github.com<mailto:notifications@github.com>> wrote:

After several tests, the rounding errors seem have nothing to do with the way I rounded them. Even I used the original values to calculate (previously I was using one more decimal, which should be essentially the same), the issue persists.

My fix, for the moment, would be keeping two decimals for the final results-after tax profits. I haven’t yet found any inconsistency in this case. I’ll try to fix the problem for one decimal as well.

On Dec 22, 2016, at 4:55 PM, Sean Wang <Sean.Wang@AEI.org<mailto:Sean.Wang@AEI.org><mailto:Sean.Wang@aei.org>> wrote:

Thanks for the tips. Seems good to go.

https://ospc.shinyapps.io/border-adjustment-calculator/

On Dec 22, 2016, at 4:23 PM, Matt Jensen <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


I think the right solution on rounding is probably to use the raw numbers in all calculations but to round everything to 10ths before it is displayed. Looks like right now you may be using rounded numbers in the calculations.

**Comment by GoFroggyRun** [comment]
okay. got you.
On Dec 22, 2016, at 5:39 PM, Matt Jensen <notifications@github.com<mailto:notifications@github.com>> wrote:

Let's keep the tenths place even if it creates inconsistencies while you try to identify the cause of the inconsistencies.

On Dec 22, 2016, at 6:37 PM, Sean.Wang <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

After several tests, the rounding errors seem have nothing to do with the way I rounded them. Even I used the original values to calculate (previously I was using one more decimal, which should be essentially the same), the issue persists.

My fix, for the moment, would be keeping two decimals for the final results-after tax profits. I haven’t yet found any inconsistency in this case. I’ll try to fix the problem for one decimal as well.

On Dec 22, 2016, at 4:55 PM, Sean Wang <Sean.Wang@AEI.org<mailto:Sean.Wang@aei.org><mailto:Sean.Wang@AEI.org><mailto:Sean.Wang@aei.org>> wrote:

Thanks for the tips. Seems good to go.

https://ospc.shinyapps.io/border-adjustment-calculator/

On Dec 22, 2016, at 4:23 PM, Matt Jensen <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


I think the right solution on rounding is probably to use the raw numbers in all calculations but to round everything to 10ths before it is displayed. Looks like right now you may be using rounded numbers in the calculations.

**Comment by GoFroggyRun** [comment]
still wasn’t quite sure why rounding error is happening.

I also notice that, when set tax rate to 100, the table will have NaN, given the formula involves something like 1/(1-tax_rate/100).

Do you need to worry about this?

On Dec 22, 2016, at 5:39 PM, Sean Wang <sean.wang@aei.org<mailto:sean.wang@aei.org>> wrote:

okay. got you.
On Dec 22, 2016, at 5:39 PM, Matt Jensen <notifications@github.com<mailto:notifications@github.com>> wrote:

Let's keep the tenths place even if it creates inconsistencies while you try to identify the cause of the inconsistencies.

On Dec 22, 2016, at 6:37 PM, Sean.Wang <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

After several tests, the rounding errors seem have nothing to do with the way I rounded them. Even I used the original values to calculate (previously I was using one more decimal, which should be essentially the same), the issue persists.

My fix, for the moment, would be keeping two decimals for the final results-after tax profits. I haven’t yet found any inconsistency in this case. I’ll try to fix the problem for one decimal as well.

On Dec 22, 2016, at 4:55 PM, Sean Wang <Sean.Wang@AEI.org<mailto:Sean.Wang@aei.org><mailto:Sean.Wang@AEI.org><mailto:Sean.Wang@aei.org>> wrote:

Thanks for the tips. Seems good to go.

https://ospc.shinyapps.io/border-adjustment-calculator/

On Dec 22, 2016, at 4:23 PM, Matt Jensen <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


I think the right solution on rounding is probably to use the raw numbers in all calculations but to round everything to 10ths before it is displayed. Looks like right now you may be using rounded numbers in the calculations.

**Comment by GoFroggyRun** [comment]
do we*

On Dec 22, 2016, at 7:39 PM, Sean Wang <sean.wang@aei.org<mailto:sean.wang@aei.org>> wrote:

still wasn’t quite sure why rounding error is happening.

I also notice that, when set tax rate to 100, the table will have NaN, given the formula involves something like 1/(1-tax_rate/100).

Do you need to worry about this?

On Dec 22, 2016, at 5:39 PM, Sean Wang <sean.wang@aei.org<mailto:sean.wang@aei.org>> wrote:

okay. got you.
On Dec 22, 2016, at 5:39 PM, Matt Jensen <notifications@github.com<mailto:notifications@github.com>> wrote:

Let's keep the tenths place even if it creates inconsistencies while you try to identify the cause of the inconsistencies.

On Dec 22, 2016, at 6:37 PM, Sean.Wang <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

After several tests, the rounding errors seem have nothing to do with the way I rounded them. Even I used the original values to calculate (previously I was using one more decimal, which should be essentially the same), the issue persists.

My fix, for the moment, would be keeping two decimals for the final results-after tax profits. I haven’t yet found any inconsistency in this case. I’ll try to fix the problem for one decimal as well.

On Dec 22, 2016, at 4:55 PM, Sean Wang <Sean.Wang@AEI.org<mailto:Sean.Wang@aei.org><mailto:Sean.Wang@AEI.org><mailto:Sean.Wang@aei.org>> wrote:

Thanks for the tips. Seems good to go.

https://ospc.shinyapps.io/border-adjustment-calculator/

On Dec 22, 2016, at 4:23 PM, Matt Jensen <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


I think the right solution on rounding is probably to use the raw numbers in all calculations but to round everything to 10ths before it is displayed. Looks like right now you may be using rounded numbers in the calculations.

**Comment by MattHJensen** [comment]
I don’t think we need to worry about it for now.
On Dec 22, 2016, at 8:41 PM, Sean.Wang <notifications@github.com<mailto:notifications@github.com>> wrote:

do we*

On Dec 22, 2016, at 7:39 PM, Sean Wang <sean.wang@aei.org<mailto:sean.wang@aei.org><mailto:sean.wang@aei.org>> wrote:

still wasn’t quite sure why rounding error is happening.

I also notice that, when set tax rate to 100, the table will have NaN, given the formula involves something like 1/(1-tax_rate/100).

Do you need to worry about this?

On Dec 22, 2016, at 5:39 PM, Sean Wang <sean.wang@aei.org<mailto:sean.wang@aei.org><mailto:sean.wang@aei.org>> wrote:

okay. got you.
On Dec 22, 2016, at 5:39 PM, Matt Jensen <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Let's keep the tenths place even if it creates inconsistencies while you try to identify the cause of the inconsistencies.

On Dec 22, 2016, at 6:37 PM, Sean.Wang <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

After several tests, the rounding errors seem have nothing to do with the way I rounded them. Even I used the original values to calculate (previously I was using one more decimal, which should be essentially the same), the issue persists.

My fix, for the moment, would be keeping two decimals for the final results-after tax profits. I haven’t yet found any inconsistency in this case. I’ll try to fix the problem for one decimal as well.

On Dec 22, 2016, at 4:55 PM, Sean Wang <Sean.Wang@AEI.org<mailto:Sean.Wang@AEI.org><mailto:Sean.Wang@aei.org><mailto:Sean.Wang@AEI.org><mailto:Sean.Wang@aei.org>> wrote:

Thanks for the tips. Seems good to go.

https://ospc.shinyapps.io/border-adjustment-calculator/

On Dec 22, 2016, at 4:23 PM, Matt Jensen <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


I think the right solution on rounding is probably to use the raw numbers in all calculations but to round everything to 10ths before it is displayed. Looks like right now you may be using rounded numbers in the calculations.

**Comment by GoFroggyRun** [comment]
I ran the following code in R:
```
> round(21.55,1)
[1] 21.6
> round(59.15,1)
[1] 59.1
```
This should explain why the web page is generating inconsistent results.

**Comment by MattHJensen** [comment]
Good catch! Feel free to push to the app anytime this morning if you didn't already.

**Pull request merged**
